[package]
name = "custom-proxy-http"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
env_logger = "0.11.7"
futures-util = "0.3.31"
log = "0.4.26"
reqwest = { version = "0.12.14", features = ["stream"] }
